<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Univ.-Prof.&nbsp;Dr.&nbsp;Marcel Lichters">
<meta name="author" content="Felix Lang">

<title>Sensory Marketing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Chapter_7_Examples_files/libs/clipboard/clipboard.min.js"></script>
<script src="Chapter_7_Examples_files/libs/quarto-html/quarto.js"></script>
<script src="Chapter_7_Examples_files/libs/quarto-html/popper.min.js"></script>
<script src="Chapter_7_Examples_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Chapter_7_Examples_files/libs/quarto-html/anchor.min.js"></script>
<link href="Chapter_7_Examples_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Chapter_7_Examples_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Chapter_7_Examples_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Chapter_7_Examples_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Chapter_7_Examples_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="citation_title" content="Sensory Marketing: Chapter 7 - Sensory Product Research">
<meta name="citation_author" content="Univ.-Prof. Dr. Marcel Lichters">
<meta name="citation_author" content="Felix Lang">
<meta name="citation_publication_date" content="2023-10-04">
<meta name="citation_cover_date" content="2023-10-04">
<meta name="citation_year" content="2023">
<meta name="citation_online_date" content="2023-10-04">
<meta name="citation_fulltext_html_url" content="https://rpubs.com/M_Lichters/PSM">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=sensR—an r-package for sensory discrimination;,citation_author=R. H. B. Christensen;,citation_author=P. B. Brockhoff;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=https://cran.r-project.org/web/packages/sensR/index.html;">
<meta name="citation_reference" content="citation_title=Sensory evaluation of food: Principles and practices;,citation_author=Harry T. Lawless;,citation_author=Hildegarde Heymann;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;">
<meta name="citation_reference" content="citation_title=Statistics for sensory and consumer science;,citation_author=Tormod Naes;,citation_author=Per B. Brockhoff;,citation_author=Oliver Tomic;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_doi=10.1002/9780470669181;">
<meta name="citation_reference" content="citation_title=Analyzing sensory data with r;,citation_author=Sébastien Lê;,citation_author=Thierry Worch;,citation_publication_date=2015;,citation_cover_date=2015;,citation_year=2015;,citation_series_title=Chapman &amp;amp;amp; hall / CRC the r series;">
<meta name="citation_reference" content="citation_title=R for marketing research and analytics;,citation_author=Chris Chapman;,citation_author=Elea McDonnell Feit;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_series_title=Use r!;">
<meta name="citation_reference" content="citation_title=Remotes: R package installation from remote repositories, including ’GitHub’;,citation_author=Gábor Csárdi;,citation_author=Jim Hester;,citation_author=Hadley Wickham;,citation_author=Winston Chang;,citation_author=Martin Morgan;,citation_author=Dan Tenenbaum;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://CRAN.R-project.org/package=remotes;">
<meta name="citation_reference" content="citation_title=Statistics for sensory and consumer science;,citation_author=Tormod Naes;,citation_author=Per B. Brockhoff;,citation_author=Oliver Tomic;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_doi=10.1002/9780470669181;">
<meta name="citation_reference" content="citation_title=Risk tables for discrimination tests;,citation_author=Pascal Schlich;,citation_publication_date=1993-01;,citation_cover_date=1993-01;,citation_year=1993;,citation_fulltext_html_url=http://dx.doi.org/10.1016/0950-3293(93)90157-2;,citation_issue=3;,citation_doi=10.1016/0950-3293(93)90157-2;,citation_volume=4;,citation_language=en;,citation_journal_title=Food Quality and Preference;">
<meta name="citation_reference" content="citation_title=Purrr: Functional programming tools;,citation_author=Lionel Henry;,citation_author=Hadley Wickham;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=https://CRAN.R-project.org/package=purrr;">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Sensory Marketing</h1>
            <p class="subtitle lead">Chapter 7 - Sensory Product Research</p>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://www.tu-chemnitz.de/wirtschaft/bwl2/index.html">Univ.-Prof.&nbsp;Dr.&nbsp;Marcel Lichters</a> </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              <a href="https://www.tu-chemnitz.de/index.html.en">
              Chemnitz University of Technology
              </a>
            </p>
        </div>
        <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://www.tu-chemnitz.de/wirtschaft/bwl2/index.html">Felix Lang</a> </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              <a href="https://www.tu-chemnitz.de/index.html.en">
              Chemnitz University of Technology
              </a>
            </p>
        </div>
      </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">Wednesday, October 4, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#loading-packages-that-we-will-use" id="toc-loading-packages-that-we-will-use" class="nav-link active" data-scroll-target="#loading-packages-that-we-will-use"><span class="header-section-number">1</span> Loading packages that we will use</a></li>
  <li><a href="#example-for-discrimination-test---triangle-test." id="toc-example-for-discrimination-test---triangle-test." class="nav-link" data-scroll-target="#example-for-discrimination-test---triangle-test."><span class="header-section-number">2</span> Example for Discrimination test - Triangle test.</a></li>
  <li><a href="#example-of-a-post-hoc-power-analyis-for-a-triangle-test" id="toc-example-of-a-post-hoc-power-analyis-for-a-triangle-test" class="nav-link" data-scroll-target="#example-of-a-post-hoc-power-analyis-for-a-triangle-test"><span class="header-section-number">3</span> Example of a Post-hoc Power Analyis for a Triangle Test</a></li>
  <li><a href="#using-posit-cloud-formerly-rstudio-cloud" id="toc-using-posit-cloud-formerly-rstudio-cloud" class="nav-link" data-scroll-target="#using-posit-cloud-formerly-rstudio-cloud"><span class="header-section-number">4</span> Using Posit Cloud (formerly RStudio Cloud)</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<hr>
<p>R analysis script presenting the examples studied in Chapter 7 of the Sensory Marketing lecture</p>
<p>In this exercise students should practice analyzing data with <a href="https://cran.r-project.org/"><em>R</em></a> and <a href="https://posit.co/products/open-source/rstudio/"><em>RStudio</em></a>. These skills will serve them well in the progress of their study time and in the future. The internet provides countless further examples. Besides, there exist very good text books (e.g., <span class="citation" data-cites="naes2010a">Naes, Brockhoff, and Tomic (<a href="#ref-naes2010a" role="doc-biblioref">2010</a>)</span>, <span class="citation" data-cites="lê2015">Lê and Worch (<a href="#ref-lê2015" role="doc-biblioref">2015</a>)</span>, <span class="citation" data-cites="chapman2019">Chapman and Feit (<a href="#ref-chapman2019" role="doc-biblioref">2019</a>)</span>).</p>
<section id="loading-packages-that-we-will-use" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Loading packages that we will use</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>R</em> is a context-sensitive language. Thus, ‘data’ will be interpreted not in the same way as ‘Data’ will.</p>
</div>
</div>
<p>In <em>R</em> most functionality is provided by additional packages.<br>
Most of the packages are well-documented, See: <a href="https://cran.r-project.org/" class="uri">https://cran.r-project.org/</a></p>
<ol type="1">
<li><p>The code chunk below first evaluates if the package <a href="https://cran.r-project.org/web/packages/pacman/index.html">pacman</a> is already installed to your machine. If yes, the corresponding package will be loaded. If not, <em>R</em> will install the package (as long as the package is still maintained on the <strong>C</strong>omprehensive <strong>R</strong> <strong>A</strong>rchive <strong>N</strong>etwork <a href="https://cran.r-project.org/"><em>CRAN</em></a>.</p></li>
<li><p>Alternatively, you can do this manually first by executing <em>install.packages(“pacman”)</em> and then <em>library(pacman)</em>.</p></li>
<li><p>The second line then loads the package <em>pacman</em></p></li>
<li><p>The third line uses the function <em>p_load()</em> from the pacman package to install (if necessary) and load all packages that we provide as arguments (e.g., <a href="https://cran.r-project.org/web/packages/tidyverse/">tidyverse</a>).</p></li>
<li><p>This only works if all packages are still available on <em>CRAN</em>. However, if a package is discontinued on <em>CRAN</em>, there is always the latest version in the archive. For our analysis we also draw on the discontinued package <a href="https://cran.r-project.org/web/packages/sensR/index.html"><em>sensR</em></a> <span class="citation" data-cites="sensR">(<a href="#ref-sensR" role="doc-biblioref">Christensen and Brockhoff 2020</a>)</span>. To install this outdated package, we use the function <em>install_version()</em> from <a href="https://cran.r-project.org/web/packages/remotes/index.html"><em>remotes</em></a> <span class="citation" data-cites="remotes">(<a href="#ref-remotes" role="doc-biblioref">Csárdi et al. 2021</a>)</span>, which expects us to provide the package name, the version we wish to install from <em>CRAN</em>s archive, and a <em>CRAN</em> mirror url.</p></li>
<li><p>Finally, the last line (<em>library(sensR)</em>) loads the package.</p></li>
</ol>
<div class="cell" data-hash="Chapter_7_Examples_cache/html/unnamed-chunk-2_58c37fb00b8c0df62e4cc2e3cbab2e08">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="st">"pacman"</span> <span class="sc">%in%</span> <span class="fu">rownames</span>(<span class="fu">installed.packages</span>())) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, SensoMineR, remotes, purrr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="st">"sensR"</span> <span class="sc">%in%</span> <span class="fu">rownames</span>(<span class="fu">installed.packages</span>())) <span class="fu">install_version</span>(<span class="at">package =</span> <span class="st">"sensR"</span>, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">version =</span> <span class="st">"1.5-2"</span>, </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">repos =</span> <span class="st">"https://cloud.r-project.org"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sensR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p>Here is the <em>R</em> session info which gives you information on my machine, all loaded packages and their version:</p>
<div class="cell" data-hash="Chapter_7_Examples_cache/html/unnamed-chunk-3_6fca827645b4feb0ff4b5c6f90026a29">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
[3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sensR_1.5-2     remotes_2.4.2.1 SensoMineR_1.26 FactoMineR_2.8 
 [5] lubridate_1.9.3 forcats_1.0.0   stringr_1.5.0   dplyr_1.1.3    
 [9] purrr_1.0.2     readr_2.1.4     tidyr_1.3.0     tibble_3.2.1   
[13] ggplot2_3.4.3   tidyverse_2.0.0 pacman_0.5.1   

loaded via a namespace (and not attached):
 [1] gtable_0.3.4         xfun_0.40            htmlwidgets_1.6.2   
 [4] ggrepel_0.9.3        lattice_0.21-8       tzdb_0.4.0          
 [7] numDeriv_2016.8-1.1  vctrs_0.6.3          tools_4.3.1         
[10] generics_0.1.3       sandwich_3.0-2       fansi_1.0.4         
[13] cluster_2.1.4        AlgDesign_1.2.1      pkgconfig_2.0.3     
[16] Matrix_1.6-1.1       KernSmooth_2.23-21   scatterplot3d_0.3-44
[19] lifecycle_1.0.3      compiler_4.3.1       munsell_0.5.0       
[22] codetools_0.2-19     leaps_3.1            htmltools_0.5.6     
[25] yaml_2.3.7           pillar_1.9.0         MASS_7.3-60         
[28] flashClust_1.01-2    DT_0.29              multcomp_1.4-25     
[31] gtools_3.9.4         tidyselect_1.2.0     digest_0.6.33       
[34] mvtnorm_1.2-3        stringi_1.7.12       reshape2_1.4.4      
[37] splines_4.3.1        fastmap_1.1.1        grid_4.3.1          
[40] colorspace_2.1-0     cli_3.6.1            magrittr_2.0.3      
[43] survival_3.5-5       utf8_1.2.3           TH.data_1.1-2       
[46] withr_2.5.1          scales_1.2.1         estimability_1.4.1  
[49] timechange_0.2.0     rmarkdown_2.25       emmeans_1.8.8       
[52] zoo_1.8-12           hms_1.1.3            evaluate_0.22       
[55] knitr_1.44           rlang_1.1.1          Rcpp_1.0.11         
[58] glue_1.6.2           rstudioapi_0.15.0    jsonlite_1.8.7      
[61] R6_2.5.1             plyr_1.8.9           multcompView_0.1-9  </code></pre>
</div>
</div>
<hr>
</section>
<section id="example-for-discrimination-test---triangle-test." class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Example for Discrimination test - Triangle test.</h1>
<p>Triangle tests are very popular in sensory product research as tests for discrimination, and help to evaluate whether consumers can significantly distinguish between product alternatives <span class="citation" data-cites="lawless2010">(see, e.g., <a href="#ref-lawless2010" role="doc-biblioref">Lawless and Heymann 2010, chap. 4.4</a>)</span>. In our lecture example on Lasagna variants, we observe the following results on the basis of n=100 consumers:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Correctly identified odd sample</th>
<th style="text-align: center;">Incorrect response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Observed</strong></td>
<td style="text-align: center;">43 (O<sub>1</sub>)</td>
<td style="text-align: center;">57 (O<sub>2</sub>)</td>
</tr>
<tr class="even">
<td><strong>Expected</strong></td>
<td style="text-align: center;">33.<span class="math inline">\(\bar{3}\)</span> (E<sub>1</sub>)</td>
<td style="text-align: center;">66.<span class="math inline">\(\bar{6}\)</span> (E<sub>2</sub>)</td>
</tr>
</tbody>
</table>
<p>In our example, analysis draws on a (Pearson) <span class="math inline">\(\chi^{2}\)</span>-test (without continuity correction). Here, the test statistic is calculated as follows:</p>
<p><span class="math inline">\(\chi^{2}_{(1)}=\sum\frac{(observed-expected)^2}{expected}=[\frac{(O_{1}-E_{1})^2}{E_{1}}]+[\frac{(O_{2}-E_{2})^2}{E_{2}}]=[\frac{(43-33.\bar{3})^2}{33.\bar{3}}]+\frac{(57-66.\bar{6})^2}{66.\bar{6}}]=2.803+1.402=4.205\)</span></p>
<p>We know from lectures in statistics that the <em>df</em> in a <span class="math inline">\(\chi^{2}\)</span>-test equal: (number of rows -1) * (number of columns -1). Thus, df=(2-1)*(2-1)=1. The degrees of freedom are 1.</p>
<p>The package <a href="https://cran.r-project.org/web/packages/sensR/">sensR</a> is providing functions to handle nearly all types of discrimination tests, including Triangle tests. We will use the function <strong>discrim()</strong>. This function allows us to specify many arguments (see help by pressing ‘F1’). We will do so for</p>
<ul>
<li>correct = the number of correct answers</li>
<li>total = total number of responses</li>
<li>conf.level = significance level (Type I error probability <span class="math inline">\(\alpha\)</span>)</li>
<li>method = the discrimination protocol applied (see lecture slides for the various options)</li>
<li>statistic = The type of analysis strategy to apply for the data (whether one wants to use normal distribution or Chi² etc.)</li>
<li>test = Whether a test for similarity or difference should be obtained.</li>
</ul>
<p>Below, we assign the results of our Triangle Discrimination test to a new object named ‘triangle_test’. Then we call for its content.</p>
<div class="cell" data-hash="Chapter_7_Examples_cache/html/unnamed-chunk-4_d33df8339f743c7db45150aba7e6bc72">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>triangle_test <span class="ot">&lt;-</span> <span class="fu">discrim</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">correct=</span> <span class="dv">43</span>, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">total=</span> <span class="dv">100</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"triangle"</span>, </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">statistic =</span> <span class="st">"score"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">test =</span> <span class="st">"difference"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>triangle_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Estimates for the triangle discrimination protocol with 43 correct
answers in 100 trials. One-sided p-value and 95 % two-sided confidence
intervals are based on the Pearson and score statistics. 

        Estimate Std. Error  Lower  Upper
pc         0.430    0.04951 0.3333 0.5328
pd         0.145    0.07426 0.0000 0.2992
d-prime    1.075    0.30276 0.0000 1.6355

Result of difference test:
Pearson X-square statistic = 4.205, df = 1, p-value: 0.02015
Alternative hypothesis: d-prime is greater than 0 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>As the results of the <span class="math inline">\(\chi^{2}\)</span>-test is significant (0.02), we have to reject H<sub>0</sub>. Thus, consumers can reliably distinguish between the new and the old lasagna.</p>
</div>
</div>
<ul>
<li>In the output above, <em>pc</em> means the percentage of correct discriminators (43/100).</li>
<li>pd stands for the estimated proportion of individuals in the (relevant) population that would detect the product difference. Which is in the case of a Triangle test: <span class="math inline">\(pd=\frac{pc-1/3}{2/3}\)</span>. Note that the confidence interval for pd has an upper limit of 29.92%. Thus, in the worst case, the true proportion of discriminators is almost as high as 30%. <span class="citation" data-cites="schlich1993">Schlich (<a href="#ref-schlich1993" role="doc-biblioref">1993</a>)</span> proposed the following limits for <em>pd</em> as <em>small</em>, <em>medium</em>, <em>large</em> differences: 0.25, 0.375, and 0.50.</li>
<li>The Thurstonian approach of transforming the number of correct answers into an estimate, called d-prime of the underlying (relative) sensory difference is an attempt to overcome the concepts of <em>pc</em> and <em>pd</em>, since these are dependent on the concrete test protocol one has applied (e.g., Triangle vs.&nbsp;3-AFC tests). The higher the value the higher is the degree of difference between the two products that were tested.</li>
</ul>
<hr>
</section>
<section id="example-of-a-post-hoc-power-analyis-for-a-triangle-test" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Example of a Post-hoc Power Analyis for a Triangle Test</h1>
<p>To get an idea about the statistical Power of a Similarity or Dissimilarity test protocol, the <a href="https://cran.r-project.org/web/packages/sensR/">sensR</a> package also provides functions that facilitate sample size planning for discrimination tests (i.e., statistical power analysis). To provide an example, we will use the d-prime estimate from the Triangle test on lasagna above (1.07) as input the determine the statistical power of the Triangle test with n=100.</p>
<p>In the code chunk below, we use the obtained d-prime as input for the function <em>d.primePwr()</em>. Furthermore, we specify all other aspects of our exemplary Triangle test.</p>
<div class="cell" data-hash="Chapter_7_Examples_cache/html/unnamed-chunk-5_cfde8a1b7067d30a1529aa347801b0e2">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>power_triangle <span class="ot">&lt;-</span> <span class="fu">d.primePwr</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">d.primeA =</span> <span class="fl">1.075</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample.size =</span> <span class="dv">100</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"triangle"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">test =</span> <span class="st">"difference"</span>, <span class="at">statistic =</span> <span class="st">"exact"</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>power_triangle</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.617578</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>With the observed effect size for the difference, our Triangle test protocol only has a power of 61.76. Thus, if the observed effect is the true effect in the underlying population, then we would have this chance to find a significant difference in a Triangle test with n=100 and <span class="math inline">\(\alpha\)</span>=5%, which is insufficient.</p>
</div>
</div>
<p>As a final remark, we can estimate how many consumers should be tested in order to obtain a sufficient statistical power based on the observed effect size for the difference, a Triangle test, and <span class="math inline">\(\alpha\)</span>=5%. For this purpose, we first establish a list of varying sample sizes below. Afterwards, we use this list as input for the <em>sample.size</em> argument of the <em>d.primePwr()</em> function. Usually, this function does not accept a list of values as arguments. To handle this problem, we additionally apply the <em>map()</em> function provided by the <a href="https://cran.r-project.org/web/packages/purrr/index.html">purrr</a> package <span class="citation" data-cites="purrr">(<a href="#ref-purrr" role="doc-biblioref">Henry and Wickham 2020</a>)</span>. In the corresponding call of <em>d.primePwr()</em> we set <strong>sample.size = .</strong>, to tell the map function to use each element of the input list as input for the sample size argument in repeated calls of <em>d.primePwr()</em>.</p>
<div class="cell" data-hash="Chapter_7_Examples_cache/html/unnamed-chunk-6_ffc19965d83a55585efe5f3c3dda5be3">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">n100 =</span> <span class="dv">100</span>, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">n200 =</span> <span class="dv">200</span>, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">n300 =</span> <span class="dv">300</span>, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">n400 =</span> <span class="dv">400</span>, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">n500 =</span> <span class="dv">500</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="sc">%&gt;%</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(<span class="sc">~</span> <span class="fu">d.primePwr</span>(</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">d.primeA =</span> <span class="fl">1.075</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample.size =</span> .,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"triangle"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">test =</span> <span class="st">"difference"</span>, <span class="at">statistic =</span> <span class="st">"exact"</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$n100
[1] 0.617578

$n200
[1] 0.8583079

$n300
[1] 0.9552637

$n400
[1] 0.9888657

$n500
[1] 0.9972308</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can see that with a sample size of n=200 and above, we realize a power of over 85%.</p>
</div>
</div>
<hr>
</section>
<section id="using-posit-cloud-formerly-rstudio-cloud" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Using Posit Cloud (formerly RStudio Cloud)</h1>
<p>If you are new to the <em>R</em> universe (rumors say there are still folks outside), it is also an option to run all of the code presented in the script via <a href="https://posit.cloud">Posit Cloud</a>. This solution allows you to analyze your data using RStudio, directly from your web browser, which comes with several advantages:</p>
<ul>
<li>For you as student its for free (just sign up)</li>
<li>No need to install <em>R</em> &amp; <em>RStudio</em></li>
<li>No need to update <em>R</em> and packages</li>
<li>All packages used are already installed and loaded in the corresponding <em>Posit Cloud</em> project <a href="https://posit.cloud/content/5201389" class="uri">https://posit.cloud/content/5201389</a>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Just make sure to create a copy of the provided project to your own account! Otherwise, results are not saved (it’s a temporary project).</p>
</div>
</div>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-chapman2019" class="csl-entry" role="listitem">
Chapman, Chris, and Elea McDonnell Feit. 2019. <em>R for Marketing Research and Analytics</em>. 2nd ed. Use r! Cham: Springer International Publishing.
</div>
<div id="ref-sensR" class="csl-entry" role="listitem">
Christensen, R. H. B., and P. B. Brockhoff. 2020. <span>“sensR—an r-Package for Sensory Discrimination.”</span> <a href="https://cran.r-project.org/web/packages/sensR/index.html">https://cran.r-project.org/web/packages/sensR/index.html</a>.
</div>
<div id="ref-remotes" class="csl-entry" role="listitem">
Csárdi, Gábor, Jim Hester, Hadley Wickham, Winston Chang, Martin Morgan, and Dan Tenenbaum. 2021. <span>“Remotes: R Package Installation from Remote Repositories, Including ’GitHub’.”</span> <a href="https://CRAN.R-project.org/package=remotes">https://CRAN.R-project.org/package=remotes</a>.
</div>
<div id="ref-purrr" class="csl-entry" role="listitem">
Henry, Lionel, and Hadley Wickham. 2020. <span>“Purrr: Functional Programming Tools.”</span> <a href="https://CRAN.R-project.org/package=purrr">https://CRAN.R-project.org/package=purrr</a>.
</div>
<div id="ref-lawless2010" class="csl-entry" role="listitem">
Lawless, Harry T., and Hildegarde Heymann. 2010. <em>Sensory Evaluation of Food: Principles and Practices</em>. 2nd ed. New York, Dordrecht, Heidelberg, London: Springer.
</div>
<div id="ref-lê2015" class="csl-entry" role="listitem">
Lê, Sébastien, and Thierry Worch. 2015. <em>Analyzing Sensory Data with r</em>. Chapman &amp; Hall / CRC the r Series. Hoboken: Taylor; Francis.
</div>
<div id="ref-naes2010a" class="csl-entry" role="listitem">
Naes, Tormod, Per B. Brockhoff, and Oliver Tomic. 2010. <em>Statistics for Sensory and Consumer Science</em>. Chichester, UK: John Wiley &amp; Sons, Ltd. <a href="https://doi.org/10.1002/9780470669181">https://doi.org/10.1002/9780470669181</a>.
</div>
<div id="ref-schlich1993" class="csl-entry" role="listitem">
Schlich, Pascal. 1993. <span>“Risk Tables for Discrimination Tests.”</span> <em>Food Quality and Preference</em> 4 (3): 141–51. <a href="https://doi.org/10.1016/0950-3293(93)90157-2">https://doi.org/10.1016/0950-3293(93)90157-2</a>.
</div>
</div></section><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@misc{dr. marcel lichters2023,
  author = {Dr. Marcel Lichters, Univ.-Prof. and Lang, Felix},
  title = {Sensory {Marketing:} {Chapter} 7 - {Sensory} {Product}
    {Research}},
  date = {2023-10-04},
  url = {https://rpubs.com/M_Lichters/PSM},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-dr. marcel lichters2023" class="csl-entry quarto-appendix-citeas" role="listitem">
Dr. Marcel Lichters, Univ.-Prof., and Felix Lang. 2023. <span>“Sensory
Marketing: Chapter 7 - Sensory Product Research.”</span> <a href="https://rpubs.com/M_Lichters/PSM">https://rpubs.com/M_Lichters/PSM</a>.
</div></div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>